[package]
name = "dnf"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
native-windows-gui = { version = "1.0.13", default-features = false, features = [
    "notice",
    "list-view",
    "listbox",
    "combobox",
    "frame",
    "textbox",
    "menu",
    "tray-notification",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_Input_Ime",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
